spring:
  application:
    name: Maratona

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USUARIO}
    password: ${DATABASE_SENHA}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USUARIO}
      password: ${NEO4J_SENHA}